#!/usr/bin/env bash
git log --pretty=format:"%ad" | awk '{print $5 "/" $2 "/" $3}' | sort | uniq -c | awk '{print $2 " " $1}' | python3 -c "import sys; print('\n'.join([f'{x.split()[0]:20}: '+int(x.split()[1])*'*' for x in sys.stdin.readlines()]))" | tr "/" " "| sort -k 1n -k 2M -k 3n

